package com.druk.llamacpp

/**
 * An interface for receiving newly generated tokens during text generation with llama.cpp.
 */
interface LlamaGenerationCallback {

    /**
     * Called whenever new tokens are generated by the language model.
     *
     * @param newTokens A byte array containing the newly generated tokens, encoded using UTF-8.
     */
    fun newTokens(newTokens: ByteArray)
}